server:
  port: 8081

nimrod:
  rsock:
    client-side:
      server1:
        host: localhost
        port: 40280
        maxConcurrentCalls: 8
      server2:
        host: localhost
        port: 40284
        maxConcurrentCalls: 4